### ISSUE TITLE
How to get the `torus` instance

### ISSUE THREAD

**Issue by leonprou** [web3connect/web3connect#102]
When connecting with Torus, how to get the `torus` instance?
With Portis is `portis` instance is put on the `provider`, can the same be done with Torus?

**Comment by pedrouid** [comment]
I have included a fix for this on #103, keep an eye on it

**Comment by pedrouid** [comment]
This has since been fixed on beta.26. Both `portis` and `torus` instances are exposed in the provider as follows:

```javascript
// portis
provider.portis

// torus
provider.torus
```
