### ISSUE TITLE
Add a "related efforts" section comparing and contrasting this lib with web3-react

### ISSUE THREAD

**Issue by pcowgill** [web3connect/web3connect#109]
Consider adding a related efforts section to the `README` comparing and contrasting this lib with `web3-react` and other alternatives, if applicable. This idea is inspired by https://github.com/RichardLitt/standard-readme

https://github.com/NoahZinsmeister/web3-react

**Comment by pedrouid** [comment]
Fixed https://github.com/web3connect/web3connect/commit/2b51143fb5c098ebb27b1b601cae7ce79a9092c3
