### ISSUE TITLE
need different or more manual provider cache behavior

### ISSUE THREAD

**Issue by dkent600** [web3connect/web3connect#113]
Bug:

1) try to connect to fortmatic.  it puts up a dialog
2) cancel out of the dialog
3) try to connect to metamask
4) formatic dialog comes up again. no way to return to choose a different provider

EXPECT:  I guess should not cache unless the user follows through and successfully connects to something.

Maybe you can do this automatically, or we should have a function that allows the dApp to cacheProvider(), just like we can manually uncache.

**Comment by pedrouid** [comment]
Need to handle connector errors better before caching the provider. But I will also add a `setCacheProvider(id: string)` method

**Comment by dkent600** [comment]
Even when I delete your localstorage key and refresh the browser, it actually write back the same key when I try to connect!

**Comment by pedrouid** [comment]
I've included fixes for these and will be releasing them as beta.29 soon
