### ISSUE TITLE
As a user, I want to be able to choose between any number of web3 browser providers

### ISSUE THREAD

**Issue by callmenick** [web3connect/web3connect#30]
Hey folks.

I just tested with two web3 provider extensions installed (Dapper & MetaMask) and it doesn't quite work. I'm wondering, is Web3Connect supposed to handle that case?

The two in question are Dapper and MetaMask. I've attached a gif to show the weirdness.

In the first bit, you can see if I have just one provider (MM), it works fine. I tested with just Dapper as well, also works fine.

In the second sequence though, you can see I have both MM and Dapper installed. Web3Connect picks up Dapper in the modal UI,  but when I press "connect", it actually connects to my MM wallet :sweat_smile: `0x59...` is the MM address. Note that in this sequence, both wallets are "unlocked" and "approved", hence there is no popup from either Dapper or MM.

I think what's happening here is the classic race to injection / overwriting. As a user, I want to avoid that issue and not have to have only one extension enabled at a time, and be able to choose either Dapper or MM from the Web3Connect interface. 

I'm not exactly sure if that's even possible given the current provider implementations, but I did speak to @crisgarner in Discord, and he mentioned he'd take a look.

Gif here:

![SLIGmN3lV2](https://user-images.githubusercontent.com/2130125/60217521-c05a5900-9821-11e9-9eaa-88a4c4a1e3cc.gif)

Also, for reference, my other musings on all of this (posted in Discord, but now captured here):

> In my mind, the ideal scenario consists a few things:
> 
> 1. The provider spec changed a bit and became more standardized
> 2. Providers don't actually inject anything (i.e. no race, no overwrites, no hacky nonsense)
> 3. Dapps -- and thus Web3Connect -- also have a standard way of interfacing with providers / allowing users to choose which one they want to use / connect, disconnect, etc.

**Comment by pedrouid** [comment]
Hey @callmenick, this is definitely an issue with browser extensions currently. We need to change how injected providers work. This is an issue that has been known prior to Web3Connect when Gnosis Safe, Mist and Metamask competed for the same namespace. Now we have Dapper as well. 

The EIP-1193 although it improves and standarizes ethereum providers, it still doesn't solve for this issue. I've chatted once with @nivida about this issue and he actually had a very interesting proposal for it. I think we should coordinate a new EIP to implement it and chat with Metamask and Dapper to integrate it to solve it.

**Comment by pedrouid** [comment]
Not currently possible as a limitation of how injected provider currently work
