### ISSUE TITLE
cancelling WalletConnect popup never fulfills the promise

### ISSUE THREAD

**Issue by dkent600** [web3connect/web3connect#38]
Cancelling out of the WalletConnect popup does not resolve nor reject the promise returned by `Web3Connect.ConnectToWalletConnect({})`.  Instead what I see is in the console:

>  index.js:206 Uncaught (in promise) Error: User closed WalletConnect modal
    at eval (index.js:206)
    at HTMLDivElement.eval (index.js:88)

I have the call wrapped in a `try/catch`.

This is a pretty significant issue since the call doesn't seem to ever complete.

**Comment by Velenir** [comment]
I tried to play with different scenarios in [codesandbox here](https://codesandbox.io/s/walletconnect-setup-w-web3connect-and-wo-s0j34)

When modal is closed promise returned from `await provider.enable();` rejects.
It should be caught to handle modal closing.
It's enough to change [walletconnect.ts:L47](https://github.com/web3connect/web3connect/blob/6fb6af26319f74e7c73db9cdcca539225958375d/src/core/connectors/walletconnect.ts#L47) to `await provider.enable().catch(reject);` to fix this, or wrap it in `try {} catch`.

Though there may be further changes needed to handle rejection in Core or Button.

**Comment by 8bu** [comment]
> 
> 
> I tried to play with different scenarios in [codesandbox here](https://codesandbox.io/s/walletconnect-setup-w-web3connect-and-wo-s0j34)
> 
> When modal is closed promise returned from `await provider.enable();` rejects.
> It should be caught to handle modal closing.
> It's enough to change [walletconnect.ts:L47](https://github.com/web3connect/web3connect/blob/6fb6af26319f74e7c73db9cdcca539225958375d/src/core/connectors/walletconnect.ts#L47) to `await provider.enable().catch(reject);` to fix this, or wrap it in `try {} catch`.
> 
> Though there may be further changes needed to handle rejection in Core or Button.

thank u, really helpful sandbox! Still caught this issue after 1 year
