### ISSUE TITLE
Provide a way to configure not to show the WalletConnect provider button

### ISSUE THREAD

**Issue by dkent600** [web3connect/web3connect#39]
There seems to be no way to configure not to show the WalletConnect provider button.  Can we have this?

Come to think of it, I don't see a way to avoid seeing injected providers either.

**Comment by crisgarner** [comment]
I feel like as a default it should work with wallet connect and injected providers. We could add props for not showing these, but can't find a proper reason. I mean these options are the ones that most users have?

**Comment by dkent600** [comment]
Suppose I only want injected plus Portis? Or Webconnect plus Fortmatic?
