### ISSUE TITLE
BUG: Multiple Connect Buttons spawn different modals?

### ISSUE THREAD

**Issue by mikheevm** [web3connect/web3connect#46]
Hi! I'd like to share some unexpected behaviour we got while integrating web3connect to our dapp using `Web3Connect.Button` component. We were planning to have two buttons: one on welcome page and one in the header. But after testing we had a bug that sometimes after clicking the provider inside the modal, the `onConnect` would fire, but modal would be still shown. After looking at the DOM, we had roughly 10 divs with `WEB3_CONNECT_MODAL_ID` id. It looks like clicking a button opened two modals at the same time.
I think the reason for this that every `Web3Connect.Button` initializes its own core inside the constructor:
https://github.com/web3connect/web3connect/blob/master/src/components/ConnectButton.tsx#L10

We solved the bug by initializing the core outside the component and using our own button component:
```
// @flow
import * as React from 'react'
import Web3Connect from 'web3connect'
import Button from '~/components/layout/Button'
import Web3Integration from '~/logic/wallets/web3Integration'

const web3Connect = new Web3Connect.Core({
  providerOptions: {
    portis: {
      id: 'PORTIS_ID', // required
      network: 'mainnet', // optional
    },
    fortmatic: {
      key: 'FORTMATIC_KEY', // required
      network: 'mainnet', // optional
    },
  },
})

web3Connect.on('connect', (provider: any) => {
  if (provider) {
    Web3Integration.setWeb3(provider)
  }
})

const ConnectButton = () => (
  <Button
    color="primary"
    variant="contained"
    minWidth={140}
    onClick={() => {
      web3Connect.toggleModal()
    }}
  >
    Connect
  </Button>
)

export default ConnectButton
```

I don't know if this is the expected behaviour, but I think it should be fixed/mentioned in the docs

**Comment by pedrouid** [comment]
ConnectButton is being deprecated
