### ISSUE TITLE
OnError causes Web3Connect to die if not explicitly provided

### ISSUE THREAD

**Issue by Cybourgeoisie** [web3connect/web3connect#69]
**Background for reproduction:** I'm using Web3Connect in a "beta" / "testing" online location that doesn't use SSL, and I'm using React and react-scripts to build the deployment code, so it took a bit of digging around to figure out what's happening here -- but Portis and WalletConnect both die when the OnError callback is called when there's no OnError function provided. (The reason they error out is that the crypto functions aren't provided in Chrome when using HTTP.)

Here's my code, using React:

```
<Web3Connect.Button className="web3connectBtn"
	providerOptions={{
		portis: {
			id: "PORTIS_ID",
			network: this.ethNetwork
		}
	}}
	onConnect={(provider: any) => {
		// stuff here ...
	}}
	onClose={() => {
		// stuff here
	}}
/>
```

The core of the bug is that OnError is being called during connection failures, but there's no callback, so the script is crashing.

The workaround is just to add a function parameter for OnError in the `Web3Connect.Button` component. As a stopgap, the OnError function should be provided in the README so that people include an OnError function when using the provided code.

Workaround:

```
<Web3Connect.Button className="web3connectBtn"
	providerOptions={{
		portis: {
			id: "PORTIS_ID",
			network: this.ethNetwork
		}
	}}
	onConnect={(provider: any) => {
		// stuff here ...
	}}
	onError={(error: any) => {
		// this has to exist
	}}
	onClose={() => {
		// stuff here
	}}
/>
```

I'm not sure how the Web3Connect maintainers want the default functionality to be when OnError is called without a callback, but IMO, a possible true fix would be to recognize when no callback is provided and to use a fallback.

**Comment by pedrouid** [comment]
You're right and technically there is an onError event but I need to go through the connectors and catch those error messages. I will include this in the next release, thanks for your feedback! 🙏
