### ISSUE TITLE
Coinbase wallet showed as Cipher

### ISSUE THREAD

**Issue by KojimaGeniy** [web3connect/web3connect#76]
Tried on our DApp and [your example](https://web3connect.com/), button showed as Cipher wallet, but trick is after login it detects provider correctly if being passed through `getProviderInfo()`.
Cipher wallet works as intended, showing it's logo in both ways.
![IMG_6643](https://user-images.githubusercontent.com/34808650/64013365-4c417780-cb28-11e9-8575-1b066c4b5dea.PNG)
![IMG_6644](https://user-images.githubusercontent.com/34808650/64013308-2d42e580-cb28-11e9-9f6a-012cbe89a77d.PNG)

**Comment by pedrouid** [comment]
I've noticed this too, does Coinbase have it's own provider check? It used to be `isToshi` but I think they change their core wallet to Cipher when it got acquired so it's triggering the `isCipher` check instead

You can find the list of known providers here: 
https://github.com/web3connect/web3connect/blob/master/src/providers/index.ts

**Comment by KojimaGeniy** [comment]
> I've noticed this too, does Coinbase have it's own provider check? It used to be `isToshi` but I think they change their core wallet to Cipher when it got acquired so it's triggering the `isCipher` check instead
> 
> You can find the list of known providers here:
> https://github.com/web3connect/web3connect/blob/master/src/providers/index.ts

I haven't been able to ask them, their discord channel is a mess, and no repo for wallet. The best info I could find is [here](https://drive.google.com/file/d/1UU9_36keso1DbKKEck4DdO19Ap1FF0ov/view) at page №16. Can it be that they injecting too late or something? And again, after enabling their wallet it can be recognized with `getProviderInfo()` as Coinbase pretty well.

**Comment by pedrouid** [comment]
Maybe we should add a special condition like the one that was added for NiftyWallet. Which could check if `result["isCipher"]` then check again for the currentProvider if `isToshi` is available and switch the provider check.

@crisgarner you did the fix for NiftyWallet, do you know if this would be a valid solution for checking Coinbase Wallet?

**Comment by pedrouid** [comment]
I've included a fix for this on master, will release as beta.29

**Comment by Fariha1123** [comment]
Hi, can I know what does injects web3 in case of coinbase browser? I have a dapp that supports wallet connect and metamask, they were straight forward to be added in web3modal but Im unsure what to set as provider for coinbase wallet? Please guide
