### ISSUE TITLE
Using from unpkg

### ISSUE THREAD

**Issue by exebook** [web3connect/web3connect#85]
We do not want to include web3connect in our main bundle, so we are trying to use it with `<script src="http://unpkg.......web3connect.js">` But it does not work for web3connect (although we managed it to work with web3.js already). Any working eample with that please? We get web3connect.Core is node defined. Or if we use `new web3connect.default.Core()` we got `e() is undefined` or other random errors that make no sense.

**Comment by pedrouid** [comment]
I haven't used unpkg with web3connect yet but you can also download the latest release bundle from our releases page

https://github.com/web3connect/web3connect/releases

**Comment by pedrouid** [comment]
Actually I just noticed that you are calling `new web3connect.default.Core()` and it should be instead `new Web3Connect.default.Core()`
