### ISSUE TITLE
Web3Connect.getProviderInfo(provider) with Authereum as provider returns `name` with value `MetaMask`

### ISSUE THREAD

**Issue by oznekenzo** [web3connect/web3connect#98]
Hey guys :] - We're saving this `name` in localStorage as their default wallet, which we use on direct logins.  The issue is, of course, that this now triggers a login using `metamask` instead of `authereum` the next time users try to login using their default wallet.

**Comment by crisgarner** [comment]
Does this only happen with Authereum?

**Comment by oznekenzo** [comment]
I presume not, everything was working in production, was only seeing this issue when trying to add Authereum.  I should mention that the provider object that was returned has both `isMetaMask` and `isAuthereum` flagged as true

**Comment by crisgarner** [comment]
Can you share some code @oznekenzo? I want to reproduce it to test it out

**Comment by oznekenzo** [comment]
```
import Web3Connect from 'web3connect';
import WalletConnectProvider from '@walletconnect/web3-provider';
import Authereum from "authereum";

const web3Connect = new Web3Connect.Core({
  providerOptions: {
    authereum: {
      package: Authereum,
      options: {},
    },
  },
});

web3Connect.on('connect', async (provider) => {
  try {
    const {
      name,
      logo,
    } = Web3Connect.getProviderInfo(provider);
    console.log('name', name); // returns MetaMask
  } catch (error) {
    console.log(error)
  }
});
```

**Comment by LiorAgnin** [comment]
@oznekenzo  @oznekenzo 
I have the same issue but with torus. after connect  getProviderInfo method returns metamask info

**Comment by oznekenzo** [comment]
@crisgarner or @pedrouid is this a quick fix? We're wanting to integrate with Authereum :)

**Comment by oznekenzo** [comment]
Any progress on this?

**Comment by miguelmota** [comment]
@oznekenzo do you still run into this issue with the latest version of web3connect and authereum?

**Comment by pedrouid** [comment]
If this is still an issue, let us know so that we can include in beta.26 release (#103)

**Comment by oznekenzo** [comment]
this worked guys, thank you
